import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	plugins: [{
		name: 'drop-browser-code',
		setup(build) {
			build.onLoad({ filter: /jszip|immediate|setimmediate/ }, (args) => {
				let code = readFileSync(args.path, 'utf8');
				code = code.replace(/typeof\s+window\s*([!=]==)\s*['"](?:undefined|object)['"]/g, 'true');
				code = code.replace(/typeof\s+document\s*([!=]==)\s*['"](?:undefined|object)['"]/g, 'true');
				code = code.replace(/"document"\s*in\s*\w+/g, '"none"in 0');
				code = code.replace(/"onreadystatechange"\s*in\s*\w+(?:\.\w+)?\.createElement\(["']script["']\)/g, 'false');
				return { contents: code, loader: 'js' };
			});
		}
	}],
	platform: 'node',
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();

	// Post-build: patch JSZip browser-specific async scheduler code
	let code = readFileSync('main.js', 'utf8');

	// 1. Remove immediate library's browser async scheduler (uses o.document.createElement("script"))
	//    Original: "document"in o&&"onreadystatechange"in o.document.createElement("script")?function(){var X=o.document.createElement("script");...}:function(){setTimeout(d,0)}
	//    Replace entire ternary with just the setTimeout fallback
	//    NOTE: [\s\S]{0,600} bounds the match so a far-away setTimeout fallback is not swallowed
	code = code.replace(
		/"document"\s*in\s*\w+\s*&&\s*"onreadystatechange"\s*in\s*\w+\.document\.createElement\("script"\)\??[\s\S]{0,600}?:\s*(function\s*\(\s*\)\s*\{\s*setTimeout\s*\(\s*\w+\s*,\s*0\s*\)\s*\})/g,
		'$1'
	);

	// 2. Remove setimmediate library's browser async scheduler (uses g.createElement("script"))
	//    Pattern: g&&"onreadystatechange"in g.createElement("script")?(h=g.documentElement,function(N){var y=g.createElement("script");...}):function(N){setTimeout(_,0,N)}
	code = code.replace(
		/\w+\s*&&\s*"onreadystatechange"\s*in\s*\w+\.createElement\("script"\)\?[\s\S]{0,600}?:\s*(function\s*\(\s*(\w+)\s*\)\s*\{\s*setTimeout\s*\(\s*\w+\s*,\s*0\s*,\s*\2\s*\)\s*\})/g,
		'$1'
	);

	// 3. Remove the `setimmediate` package's dynamic <script> injection used as a
	//    browser async scheduler. Obsidian's ESLint rejects any dynamic
	//    `document.createElement("script")`, even if the branch is never hit at
	//    runtime. Collapse the whole ternary to its setTimeout fallback and
	//    neutralize the dead `function m(){...}` scheduler.
	const SCRIPT_RE = /createElement\(["']script["']\)/g;
	const hasScriptInjection = SCRIPT_RE.test(code);
	SCRIPT_RE.lastIndex = 0;
	if (hasScriptInjection) {
		// setimmediate: "document"in global&&"onreadystatechange"in global.document.createElement("script") ? injectScript :setTimeout fallback
		code = code.replace(/\):"document"in global&&"onreadystatechange"in global\.document\.createElement\("script"\)\?[\s\S]{0,700}?ax=function\(\)\{setTimeout\((\w+),0\)\}/, '):ax=function(){setTimeout($1,0)}');
		// setimmediate: dead `function m(){... a.createElement("script") ...}` never wired into the scheduler chain
		code = code.replace(/function m\(\)\{var v=\w+\.documentElement;[\s\S]{0,300}?\w+\.createElement\("script"\)[\s\S]{0,300}?\}\}/, 'function m(){}');
	}

	writeFileSync('main.js', code);
	process.exit(0);
} else {
	await context.watch();
}
