import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync, copyFileSync, unlinkSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * 依赖里「动态注入 <script>」的浏览器异步调度代码。
 *
 * 这几处都落在 `process.browser` 为假、或 `canUseNextTick()` 为真的**死分支**里，
 * 运行时永远不会执行，但 Obsidian 插件审核的 no-dynamic-script 规则只看源码文本，
 * 所以必须在打包阶段清掉。
 *
 * 这里踩过两个坑，正则必须同时容忍：
 * 1. `immediate` 源码用的是**单引号**（`'document' in global`）——只匹配双引号会静默漏掉；
 * 2. 标识符可能含 `$`（压缩后出现 `$x`）——`\w+` 匹配不到，必须用 `[\w$.]`。
 */
const SCRIPT_CALL = "[\\w$.]+\\.createElement\\(\\s*['\"]script['\"]\\s*\\)";
/** `'document' in X && 'onreadystatechange' in X.document.createElement('script')` */
const RE_SCRIPT_COND_FULL = new RegExp("['\"]document['\"]\\s*in\\s*[\\w$.]+\\s*&&\\s*['\"]onreadystatechange['\"]\\s*in\\s*" + SCRIPT_CALL, 'g');
/** `X && 'onreadystatechange' in X.createElement('script')` */
const RE_SCRIPT_COND_AND = new RegExp("[\\w$.]+\\s*&&\\s*['\"]onreadystatechange['\"]\\s*in\\s*" + SCRIPT_CALL, 'g');
/** 裸的 `'onreadystatechange' in X.createElement('script')` */
const RE_SCRIPT_COND_BARE = new RegExp("['\"]onreadystatechange['\"]\\s*in\\s*" + SCRIPT_CALL, 'g');

/**
 * setimmediate 的 `installReadyStateChangeImplementation`：函数体里是**裸的**
 * `doc.createElement("script")`，不在任何条件里，条件折叠删不掉它。
 *
 * 它只在 `canUseNextTick()` / `canUsePostMessage()` / `canUseMessageChannel()` 全为假时才被调用，
 * 而 Obsidian 的 Electron 渲染进程里 `canUseNextTick()` 恒为真 —— 该函数不可达。
 * 把函数体换成 setTimeout 兜底实现（语义上等价于它后面那个 installSetTimeoutImplementation），
 * 产物里就不会再有动态脚本注入。
 */
const RE_SETIMMEDIATE_READYSTATE = /function\s+installReadyStateChangeImplementation\s*\(\s*\)\s*\{[\s\S]{0,1500}?html\.appendChild\(script\);\s*\};\s*\}/;

/**
 * 把浏览器分支的条件整体折叠成字面量 `false`。
 *
 * 这样 esbuild 的常量折叠会直接把那一整段分支删掉，产物里不会再出现 `createElement("script")`。
 * 比起事后对**压缩产物**做文本手术（变量名一变就静默失效），在源码阶段折叠可靠得多。
 */
function dropScriptInjectionConditions(code) {
	code = code.replace(RE_SCRIPT_COND_FULL, 'false');
	code = code.replace(RE_SCRIPT_COND_AND, 'false');
	return code.replace(RE_SCRIPT_COND_BARE, 'false');
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	plugins: [{
		name: 'drop-browser-code',
		setup(build) {
			// 过滤范围必须覆盖**所有** js 文件：mammoth 这类浏览器版预打包产物会把
			// immediate / setimmediate 内联进来，路径里既没有 "immediate" 也没有 "jszip"，
			// 只按包名过滤会漏掉它们（2026-09 那次构建护栏报警就是这么来的）。
			build.onLoad({ filter: /\.(?:js|mjs|cjs)$/ }, (args) => {
				let code = readFileSync(args.path, 'utf8');
				const original = code;
				// 先折叠 script 注入条件，再做其它替换：顺序反了条件就被改得匹配不上了
				code = dropScriptInjectionConditions(code);
				if (/jszip|immediate|setimmediate/.test(args.path)) {
					code = code.replace(/typeof\s+window\s*([!=]==)\s*['"](?:undefined|object)['"]/g, 'true');
					code = code.replace(/typeof\s+document\s*([!=]==)\s*['"](?:undefined|object)['"]/g, 'true');
					code = code.replace(/"document"\s*in\s*\w+/g, '"none"in 0');
					code = code.replace(/"onreadystatechange"\s*in\s*\w+(?:\.\w+)?\.createElement\(["']script["']\)/g, 'false');
					code = code.replace(RE_SETIMMEDIATE_READYSTATE, 'function installReadyStateChangeImplementation() { installSetTimeoutImplementation(); }');
				}
				if (code === original) return null;
				return { contents: code, loader: 'js' };
			});
		}
	}],
	platform: 'node',
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	// esbuild 在 rebuild() 时就会把「未打补丁」的 bundle 直接写到 main.js，
	// 所以先留一份上一次的产物：护栏不过时用它还原，避免磁盘上留下坏包。
	const BACKUP = 'main.js.guardbak';
	let restoredFrom = null;
	try {
		copyFileSync('main.js', BACKUP);
		restoredFrom = BACKUP;
	} catch {
		/* 首次构建，本来就没有 main.js */
	}

	await context.rebuild();

	// Post-build: patch JSZip browser-specific async scheduler code
	let code = readFileSync('main.js', 'utf8');

	// 1. Remove immediate library's browser async scheduler (uses o.document.createElement("script"))
	//    Original: "document"in o&&"onreadystatechange"in o.document.createElement("script")?function(){var X=o.document.createElement("script");...}:function(){setTimeout(d,0)}
	//    Replace entire ternary with just the setTimeout fallback
	//    NOTE: [\s\S]{0,600} bounds the match so a far-away setTimeout fallback is not swallowed
	code = code.replace(
		/"document"\s*in\s*\w+\s*&&\s*"onreadystatechange"\s*in\s*\w+\.document\.createElement\("script"\)\??[\s\S]{0,600}?:\s*(function\s*\(\s*\)\s*\{\s*setTimeout\s*\(\s*\w+\s*,\s*0\s*\)\s*\})/g,
		'$1'
	);

	// 2. Remove setimmediate library's browser async scheduler (uses g.createElement("script"))
	//    Pattern: g&&"onreadystatechange"in g.createElement("script")?(h=g.documentElement,function(N){var y=g.createElement("script");...}):function(N){setTimeout(_,0,N)}
	code = code.replace(
		/\w+\s*&&\s*"onreadystatechange"\s*in\s*\w+\.createElement\("script"\)\?[\s\S]{0,600}?:\s*(function\s*\(\s*(\w+)\s*\)\s*\{\s*setTimeout\s*\(\s*\w+\s*,\s*0\s*,\s*\2\s*\)\s*\})/g,
		'$1'
	);

	// 3. Remove the `setimmediate` package's dynamic <script> injection used as a
	//    browser async scheduler. Obsidian's ESLint rejects any dynamic
	//    `document.createElement("script")`, even if the branch is never hit at
	//    runtime. Collapse the whole ternary to its setTimeout fallback and
	//    neutralize the dead `function m(){...}` scheduler.
	const SCRIPT_RE = /createElement\(["']script["']\)/g;
	const hasScriptInjection = SCRIPT_RE.test(code);
	SCRIPT_RE.lastIndex = 0;
	if (hasScriptInjection) {
		// setimmediate: "document"in global&&"onreadystatechange"in global.document.createElement("script") ? injectScript : setTimeout fallback
		// NOTE: variable names (ax/lx/...) are minifier-chosen and change between builds; match generically
		code = code.replace(/\):"document"in global&&"onreadystatechange"in global\.document\.createElement\("script"\)\?[\s\S]{0,700}?:(\w+)=function\(\)\{setTimeout\((\w+),0\)\}/, '):$1=function(){setTimeout($2,0)}');
		// setimmediate: dead `function m(){... a.createElement("script") ...}` never wired into the scheduler chain
		code = code.replace(/function m\(\)\{var v=\w+\.documentElement;[\s\S]{0,300}?\w+\.createElement\("script"\)[\s\S]{0,300}?\}\}/, 'function m(){}');
	}

	// 4. Neutralize the bare `eval` reference inside docx's bundled es-abstract intrinsics table.
	//    es-abstract stores "%eval%" in its intrinsics map but never invokes it, so replacing the
	//    reference with `void 0` is functionally inert and silences Obsidian's `no-eval` lint.
	code = code.replace(/"%eval%"\s*:\s*eval\b/g, '"%eval%": void 0');

	// ---------------------------------------------------------------------------
	// 5. 出口护栏：上面 4 条正则依赖压缩产物的具体形态，esbuild / 依赖升级后可能**静默失效**，
	//    结果是构建仍然成功、但 main.js 里带着会被 Obsidian 插件审核拒收的代码。
	//    这里显式断言终态，不满足就构建失败，把「静默产出坏包」变成「立刻报错」。
	// ---------------------------------------------------------------------------
	const GUARDS = [
		{
			name: 'createElement("script")',
			re: /createElement\(["']script["']\)/g,
			hint: '浏览器动态注入 <script> 的代码没被剥掉 → 检查上面 #1 / #2 / #3 三条正则',
		},
		{
			name: "eval( 调用",
			re: /eval\s*\(/g,
			hint: '裸 eval 调用没被中和 → 检查上面 #4 这条正则',
		},
		{
			name: '"%eval%": eval',
			re: /"%eval%"\s*:\s*eval\b/g,
			hint: 'docx 里 es-abstract 的 %eval% 表项没被中和 → 检查上面 #4 这条正则',
		},
	];

	const failures = [];
	for (const g of GUARDS) {
		const hits = code.match(g.re);
		if (hits && hits.length > 0) failures.push(`  - ${g.name}：命中 ${hits.length} 次。${g.hint}`);
	}
	if (failures.length > 0) {
		// esbuild 已经把这个未打补丁的 bundle 写到 main.js 了，必须撤掉。
		let restored = '已删除本次产物 main.js';
		try {
			if (restoredFrom) {
				copyFileSync(BACKUP, 'main.js');
				unlinkSync(BACKUP);
				restored = '已将 main.js 还原为上一次的产物';
			} else {
				unlinkSync('main.js');
			}
		} catch {
			restored = '（清理失败，请手动检查 main.js）';
		}
		console.error('\n✖ main.js 未通过构建护栏检查，构建中止：');
		console.error(failures.join('\n'));
		console.error(`  ${restored}。`);
		console.error('  若不修，Obsidian 插件审核会因动态脚本注入 / no-eval 规则直接拒收。\n');
		process.exit(1);
	}

	if (restoredFrom) {
		try {
			unlinkSync(BACKUP);
		} catch {
			/* 删不掉就算了，只是留个临时文件 */
		}
	}
	writeFileSync('main.js', code);
	console.log('✓ 构建护栏通过：无 createElement("script")、无裸 eval 调用');
	process.exit(0);
} else {
	await context.watch();
}
